# Generated by Django 5.2 on 2026-02-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emission_city',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('emission_type', models.CharField(choices=[('1', 'Emissão'), ('2', 'Remoção'), ('3', 'Bunker')], max_length=100)),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=200, null=True)),
                ('obs', models.CharField(blank=True, max_length=150, null=True)),
                ('activity', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('municipio', models.CharField(blank=True, max_length=150, null=True)),
                ('id_municipio', models.IntegerField(blank=True, null=True)),
                ('valores_anuais', models.JSONField(default=dict, help_text='Dicionario com ano chave e emissão como valor')),
            ],
        ),
    ]
